apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-cert
  namespace: agc-lab
spec:
  secretName: lab-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "${LAB_DOMAIN}"
